import { FormData } from 'formdata-node'; // Correct import for FormData
import { fileFromPath } from 'formdata-node/file-from-path';
import axios from 'axios';
import dotenv from 'dotenv';
dotenv.config();


const uploadEstateObject = async () => {
  const filePath = "./uiHouse.png";

  // Ensure file exists
  try {
    const file = await fileFromPath(filePath); // Create a File object from the file path

    const formData = new FormData();
    formData.append("title", "Beautiful House");
    formData.append("address", "123 Main Street");
    formData.append("city", "Los Angeles");
    formData.append("state", "CA");
    formData.append("zipCode", "90001");
    formData.append("images", file); // Add the file directly using fileFromPath
    formData.append("price", 750000);
    formData.append("bedrooms", 3);
    formData.append("bathrooms", 2);
    formData.append("garage", 1);
    formData.append("sqft", 2000);
    formData.append("lotSize", 8000);
    formData.append("isPublished", true);
    formData.append("description", "A lovely home with modern amenities.");

    console.log([...formData]); // Debug FormData content

    const bearerToken = `Bearer ${process.env.ACCESS_TOKEN || ""}`;
    // Make POST request
    const response = await axios.post(
     process.env.API_BASE_URL,
      formData,
      {
        headers: {
          Authorization: bearerToken,
          "Accept-Language": "en-US,en;q=0.8",
          ...formData.headers, // Use headers generated by FormData
        },
        maxContentLength: Infinity,
        maxBodyLength: Infinity,
      }
    );
    console.log("Upload successful:", response.data);
  } catch (error) {
    console.error(
      "Error uploading data:",
      error.response?.data || error.message
    );
  }
};

uploadEstateObject();
