name: E2E on Chrome
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  Axios-Mocha-Test:
    runs-on: ubuntu-latest
    name: E2E Tests with Axios and Mocha/Chai
    steps:
      # Step 1: Checkout the Repository
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # Step 2: Set Up Node.js Environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the desired Node.js version

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          npm install

      # Step 4: Run Mocha/Chai Tests
      - name: Run Tests
        run: |
          npx mocha "tests/**/*.test.js"
