name: PROJECT

on:
  workflow_dispatch: # Allows manual triggering
  pull_request:
    types: [opened, reopened, edited, synchronize]
  push:
    branches:
      - master
      - staging
    paths:
      - 'API-TESTING/**' # Trigger only for changes in the API-TESTING folder
      - 'package.json'
      - 'package-lock.json' # Trigger for changes to dependency files

jobs:
  Axios-Mocha-Test:
    runs-on: ubuntu-latest
    name: E2E Tests with Axios and Mocha/Chai

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set Up Node.js Environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm' # Cache dependencies for faster builds

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm ci # Faster and ensures consistent dependency versions

      # Step 4: Run Mocha/Chai Tests
      - name: Run Tests
        run: npm test # Uses the `test` script from package.json

      # Step 5: Upload Test Results (Optional)
      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: mochawesome-report/
